# Generated by Django 4.0.3 on 2022-04-04 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-added_date']},
        ),
        migrations.AlterModelOptions(
            name='resolution',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='date_approved',
            field=models.DateField(default=datetime.datetime(2022, 4, 4, 8, 12, 41, 421196, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
