# Generated by Django 4.0.5 on 2022-06-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0002_alter_certificateimage_options_resolution_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateimage',
            name='ocr',
            field=models.TextField(blank=True, default=''),
        ),
    ]
