# Generated by Django 4.0.3 on 2022-04-06 23:11

from django.db import migrations, models
import django.utils.timezone
import resolutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0002_alter_certificate_options_alter_resolution_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateimage',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='resolution',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='resolution',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='certificateimage',
            name='image',
            field=models.ImageField(upload_to=resolutions.models.CertificateImage.certificate_image_path),
        ),
    ]
